# Site settings
title: ActuallyAmity/itsamitea # The title of your site
description: Amity is a content creator who has way too much time on their hands! # Short description of your site that will appear in search engines
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://ActuallyAmity.github.io' # The base hostname & protocol for your site

# Build settings
client:
  intro: whats up gamers im # Hello, I'm { name }!
  name: amity # John Doe | Jane D.
  profession: 'Content Creator, Pro Kart Driver and Loud Annoying Person' # Doer of things
  portrait_url: https://static-cdn.jtvnw.net/jtv_user_pictures/ed62e830-5212-422e-9aa9-724205d2f539-profile_image-300x300.png # Leave blank to use local portrait in assets/

social:
  - platform: Twitch
    handle: itsamitea
  - platform: YouTube
    handle: '@actuallyamity'
  - platform: Twitter
    handle: amitylonghead
  - platform: Twitter
    handle: alastorkarting
  - platform: Reddit
    handle: r/itsamity

theme: flow
colors:
  preset:
    3
    # 1 = Elegant Lavender
    # 2 = Candy Crush
    # 3 = Cotton Candy
    # 4 = Coral Reef
  use_custom: # Toggle colors defined below this
  primary:
  secondary:
  tertiary:
  accent:
  accent_alt:
  text:

exclude:
  - serve.rb
  - README.md
